#!/usr/bin/env node
// Validate workshop packs with the same rules the dsh-mv plugin applies when installing them:
// layout and size limits, no audio, separately licensed declared lyrics, mv.json schema, static sandbox
// checks on scene scripts, and a dry run in node:vm. Bitmap outputs record drawing API
// calls only: they do not compile GPU shaders, decode images, or validate visible pixels.
//
//   node scripts/validate.mjs                 all packs
//   node scripts/validate.mjs --changed BASE  also fail if a PR touches files outside packs/<id>/
import { execFileSync } from 'node:child_process'
import { existsSync, readdirSync, statSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { validateWorkshopPack } from './vendor/mv-workshop.mjs'
import { checkScene } from './vendor/mv-scene-host.mjs'
import { verifyBrowserEvidence } from './browser-evidence.mjs'
import { PACKS, ROOT, packFiles, packIds, readPackText, readPackBytes } from './lib.mjs'

const args = process.argv.slice(2)
const base = args.includes('--changed') ? args[args.indexOf('--changed') + 1] : null
let failed = false
const fail = message => { failed = true; console.log(`::error::${message}`) }
const warn = message => console.log(`::warning::${message}`)

let only = null
if (base) {
  const changed = execFileSync('git', ['diff', '--name-only', `${base}...HEAD`], { cwd: ROOT, encoding: 'utf8' }).split('\n').filter(Boolean)
  const maintainer = process.env.WORKSHOP_MAINTAINER === 'true'
  const outside = changed.filter(path => !path.startsWith('packs/'))
  if (outside.length && !maintainer) fail(`Pull requests from contributors may only change files under packs/<id>/. Outside: ${outside.join(', ')}`)
  if (changed.includes('index.json') && !maintainer) fail('index.json is generated by CI after merge; do not edit it in a pull request.')
  only = new Set(changed.filter(p => p.startsWith('packs/')).map(p => p.split('/')[1]))
  console.log(`changed packs: ${[...only].join(', ') || '(none)'}`)
}

const ids = packIds()
for (const id of ids) {
  if (only && !only.has(id)) continue
  const files = packFiles(id)
  const result = await validateWorkshopPack({ id, files, readText: readPackText(id), readBytes: readPackBytes(id) })
  for (const e of result.errors) fail(`packs/${id}: ${e}`)
  for (const w of result.warnings) warn(`packs/${id}: ${w}`)
  if (result.errors.length) continue
  const pack = result.pack
  if (pack.canvas?.renderer === 'script') {
    const source = readPackText(id)(pack.canvas.script)
    const duration = pack.duration ?? result.meta.duration ?? 180
    const times = [0.5, duration * 0.25, duration * 0.5, duration * 0.75, Math.max(0, duration - 1)].map(t => Math.round(t * 10) / 10)
    // 0.9.1: scripts get canvas.assets (JSON shards merged like the panel does) in setup(info.assets).
    const assets = {}, unavailableBitmapAssets = []
    for (const [name, value] of Object.entries(pack.canvas.assets ?? {})) {
      const list = Array.isArray(value) ? value : [value]
      if (!list.every(p => /\.json$/i.test(p))) {
        warn(`packs/${id}: canvas.assets.${name} is an image; CI does not decode image assets. Verify this scene in the browser.`)
        unavailableBitmapAssets.push(name)
        continue
      }
      const shards = list.map(p => JSON.parse(readPackText(id)(p)))
      const merged = {}
      for (const shard of shards) for (const [k, v] of Object.entries(shard ?? {})) { if (Array.isArray(v) && Array.isArray(merged[k])) merged[k] = merged[k].concat(v); else if (!(k in merged)) merged[k] = v }
      assets[name] = shards.length === 1 ? shards[0] : merged
    }
    const info = { duration, title: pack.title, artist: pack.artist ?? '', sections: pack.sections ?? [], bpm: pack.canvas.bpm ?? 0, beatOffset: pack.canvas.beatOffset ?? 0, assets }
    // 0.9.2: webgl scripts also paint per-frame on a sized canvas; pixels / webgl both run at canvas.size.
    const output = pack.canvas.output === 'pixels' || pack.canvas.output === 'webgl' ? pack.canvas.output : 'text'
    const sizes = (output === 'text') ? [[100, 32], [60, 18]] : [pack.canvas.size]
    for (const [cols, rows] of sizes) {
      const check = checkScene(source, { times, cols, rows, info, unavailableBitmapAssets, ...(output !== 'text' ? { output, size: pack.canvas.size } : {}) })
      if (check.requiresBrowserValidation || check.ok && output !== 'text' && pack.canvas.fonts?.length) {
        const evidencePath = join(ROOT, 'validation', `${id}-${result.meta.version}.json`)
        let evidence = null
        try { evidence = JSON.parse(readFileSync(evidencePath, 'utf8')) } catch {}
        const errors = verifyBrowserEvidence(evidence, { id, version: result.meta.version, files })
        if (errors.length) fail(`packs/${id}: Host cannot rasterize this scene; verified maintainer browser evidence required: ${errors.join('; ')}`)
        else warn(`packs/${id}: real pixel readback requires browser QA; matching maintainer evidence verified for all ${files.length} files. Host does not validate GPU pixels.`)
      }
      else if (!check.ok) fail(`packs/${id}: scene script fails in the sandbox (${cols}x${rows}): ${check.problems.join('; ')}`)
      else for (const p of check.problems) warn(`packs/${id}: ${p}`)
    }
  }
  console.log(`ok packs/${id} (${files.length} files, ${files.reduce((s, f) => s + f.size, 0)} bytes, license ${result.meta.license})`)
}
// Loose files directly in packs/ are not allowed.
if (existsSync(PACKS)) for (const name of readdirSync(PACKS)) if (!statSync(join(PACKS, name)).isDirectory() && name !== '.gitkeep') fail(`packs/${name}: put files inside packs/<id>/`)
if (failed) { console.log('validation failed'); process.exit(1) }
console.log(`validated ${only ? only.size : ids.length} pack(s)`)
